# fly.toml app configuration file generated for hot-dog-lingering-dream-2014 on 2025-04-12T09:02:51-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hot-dog-lingering-dream-2014'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
